name: "Deploy Pages"

on:
  push:
    branches:
      - "main"
    paths:
      - "555722/**"
  workflow_dispatch:

permissions:
  contents: "read"
  pages: "write"
  id-token: "write"

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: "github-pages"
      url: "${{ steps.deployment.outputs.page_url }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/configure-pages@v5"
      - uses: "actions/upload-pages-artifact@v3"
        with:
          path: "./555722/"
      - uses: "actions/deploy-pages@v4"
