name: "Deploy Pages"
"on":
  push:
    branches:
      - "main"
    paths-ignore:
      - "555722/**"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "555722/**"
  workflow_dispatch:

permissions:
  contents: "read"
  pages: "write"
  id-token: "write"

jobs:
  build:
    permissions:
      checks: write
      pull-requests: write
      contents: write

    concurrency:
      group: "${{ github.workflow }}-${{ github.ref_name }}"
      cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - run: ./gradlew check
      - name: Merge for Dependabot PRs
        run: |
          gh pr merge --auto --rebase --delete-branch "${{ github.event.pull_request.html_url }}"
        if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
